# Generated by Django 4.1 on 2022-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fanra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cast", models.ManyToManyField(blank=True, to="fanra.person")),
            ],
        ),
    ]
