# Generated by Django 4.1 on 2022-08-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fanra", "0002_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ref",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
