# Generated by Django 4.1 on 2022-08-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fanra", "0004_alter_person_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fanra.movie"
            ),
        ),
    ]
