# Generated by Django 4.1 on 2022-08-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fanra", "0003_movie_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="ref",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
