# Generated by Django 4.1.5 on 2023-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fanra", "0007_remove_person_ref_movie_image_alter_movie_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celeb1", models.CharField(max_length=255)),
                ("celeb2", models.CharField(max_length=255)),
            ],
        ),
    ]
